# -*- coding: utf-8 -*-
"""progrmacion 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQ7RwgM04RZdvqA3_gQhX091J2pr6fvH

**
# corte 1 **
"""

print('hola mundo')

nombre =input("cual es tu nombre")

print("hola mundo de ",nombre)

nombre = input("que es este dato ")

print("ese dato es igual a",dato)

nombre="jeronimo"
edad=28
altura=1.67
correo="jeronimoruizreyes@wye"
soltero=True

print("tipo de dato:")
print(type(nombre))
print(type(soltero))
print(type(altura))
print(type(correo))
print(type(edad))

print("hola",nombre,"tienes," edad,-10)
print ("tipo de data")
print
print(type(nombre))