# -*- coding: utf-8 -*-
"""tarea .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFiTpHRxTdvuNshN5bdRasda8Y2M405N
"""

empanada = float(input("costo de empanadas: "))
jugo = float(input("costo de jugos: "))
papa_reyena = float(input("costo  de papas reyenas: "))

subtotal =empanada + jugo + papa_reyena
print ("subtotal",subtotal)
descuento = subtotal * 0.10
print ("descuento", descuento)
total = subtotal - descuento
print ("total",total)
iva = total * 0.19
print ("iva", iva)
total_a_pagar = total + iva
print ("total_a_pagar",total_a_pagar)
total_a_pagar= total - descuento
print ("total_a_pagar",total_a_pagar)
total_a_pagar =total + iva - descuento
print("total_a_pagar menosdescuento_mas_iva",total_a_pagar)



print("viajes_valor_tarea")
distacia = float(input("distacia:"))
rendimiento = float(input("rendimiento:"))
cantidad_galones =distacia/rendimiento
print ("galones",cantidad_galones)
valor_galon = 4.5
costo_combustible=cantidad_galones*valor_galon
print("costo_combustible",costo_combustible)
porcentaje = 0.08
costo_porcentaje = porcentaje *  costo_combustible
costo_total = costo_combustible +costo_porcentaje
print("costo_total",costo_total)
personas= costo_total / 3
print("costo_por_persona",personas)
viaje_completo = costo_total + costo_total
print("viaje_completo",viaje_completo)