# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYSLF1Ma2davJO7pUTnSfQjcGo4tGZ3T
"""

"CARRERA DE BUSES"
import os
import random
import time

GREN = "\033[32m"
END = "\033[0m"

def buses(n1, n2):
    output = []
    output.append(115 * "-")
    output.append((n1 * " ") + "_______________  " + ((100 - n1) * " ") + "|")
    output.append((n1 * " ") + "|__|__|__|__|__|___ " + ((97  - n1) * " ") + "|")
    output.append((n1 * " ") + "|    RED BULL     |)" + ((96  - n1) * " ") + "|")
    output.append((n1 * " ") + "|~~~@~~~~~~~~~@~~~|)" + ((95  - n1) * " ") + "|")
    output.append(115 * "_")
    output.append((n2 * " ") + "_______________  " + ((100 - n2) * " ") + "|")
    output.append((n2 * " ") + "|__|__|__|__|__|___ " + ((97  - n2) * " ") + "|")
    output.append((n2 * " ") + "|    MONSTER      |)" + ((96  - n2) * " ") + "|")
    output.append((n2 * " ") + "|~~~@~~~~~~~~~@~~~|)" + ((95  - n2) * " ") + "|")
    output.append(115 * "_")
    return "\n".join(output)

a = 0
b = 0
gano = None  # Inicializa 'gano' aquí

os.system("cls" if os.name == "nt" else "clear")
presentacion = """
        <<<<<<<<<<< carrera de buses >>>>>>>>>>
            RED BULL VS MONSTER """
print(presentacion)
time.sleep(3)

while a < 97 and b < 97:
    c = random.randint(1, 2)
    if c == 1:
        a += 1
    if c == 2:
        b += 1
    os.system("cls" if os.name == "nt" else "clear")
    print(buses(a, b))
    time.sleep(0.07)

if a >= 97:
    gano = "RED BULL"
if b >= 97:
    gano = "MONSTER"

print(f"{GREN}GANÓ LA CARRERA: {gano}{END}")



"""clase 07/ 09 -ciclos for while"""

num1 = int (input("dame un numero "))
num2 = int (input("dame un numero "))
num3 = int (input("dame un numero "))
suma = num1 + num2 + num3
print ("la suma es ",2suma)

cuantosnumerosquieressumar = int (input("cuantos numeros deaseas sumar "))
acumuladosuma  = 0


for i in range ( cuantosnumerosquieressumar ):
  numero = int (input("dame el numero que quiero sumar"))
  acumuladosuma  = acumuladosuma  + numero


print("resultado ", acumuladosuma )

for i in range (3) :
  print ("esta por dentro del bucle", i, "vez")
print ("esta por fuera")

for i in range  ( 5) :
  print ("vuelta",i)

#caso 1
for i in range ( 5 ) :
  print ("i = ", i)



#caso 2

for i in range (0 , 50, 5) :
  print ("cuenta de 5 en 5 ", i)

 #caso3


for  i in range (1 , 5) :
     print ("pendejo ", i )

notas = [3.5 , 5 , 4.3]
suma = 0
for nota in notas :
  suma = suma + nota
print ("promedio:", suma /len (notas ))

# ciclo why  no sabemos cuando va parar  , no sabe cuanta vuekta va  dar el ciclo
n =  -5
while n < 5 :
  print ( n )
  n = n - 1
print("!despegue!")

#punto 1
#pedido  -[nombre -0 , prducto-1, totalpagar-2 yapago-3, direccion-4]
#pedido = [nombre-0 , productos-1, totalpagar-2, yapago-3, direccion-4]
pedido = ["Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"]

#Lista creada ok

print("Nombre cliente: ", pedido[0])
print("Direccion: ", pedido[-1])

#PUNTO 2
pedido[1]=pedido[1]+2
print(pedido)
pedido[1]=5
print(pedido)

pedido[2]=62300.0
pedido[3]=True

print(pedido)

"""Enunciado
Doña Marta tiene una tienda de barrio y recibe pedidos por WhatsApp. Para no perder el hilo, guarda cada pedido en una sola lista con estos datos, en este orden: el nombre del cliente (texto), el número de productos (entero), el total a pagar (decimal), si ya pagó (verdadero o falso) y la dirección de entrega (texto). El pedido de hoy es el de Laura:
pedido = ["Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"]
Durante la mañana el pedido va cambiando y doña Marta necesita que tu programa lo vaya actualizando sobre la misma lista, sin volver a crearla desde cero. Sigue las instrucciones en orden y usa un print para mostrar el resultado de cada paso.
Qué debe hacer tu programa
1. Crea la lista e imprime el nombre del cliente (índice positivo) y la dirección de entrega (índice negativo, sin contar cuántos elementos hay).
2. Laura agregó dos productos más y el total subió a $62.300. Además, ya pagó por transferencia. Corrige esos tres datos directamente en sus posiciones.
3. Doña Marta quiere guardar el teléfono de Laura, "3001234567" (como texto), justo después del nombre, y el nombre del domiciliario, "Andrés", al final de la lista.
4. Agrega al final la hora estimada de entrega: 10 (hora) y 30 (minutos), cada uno como un elemento independiente de la lista. Imprime la lista completa y cuántos elementos tiene.
5. Usando :, imprime en un print distinto cada uno de estos cortes: (a) nombre y teléfono; (b) número de productos, total y estado de pago; (c) los tres últimos datos; (d) toda la lista en orden inverso.
Entrega: escribe el programa en Python, ejecútalo y anexa una captura de pantalla del código y otra del resultado impreso en consola.
Preguntas trampa
A. Un compañero resolvió el paso 4 con otra instrucción y su lista quedó con 8 elementos en vez de 9. ¿Qué hizo diferente y qué obtiene al imprimir el último elemento de su lista?

B. Otro compañero, ya hecho el paso 3, escribe pedido[4] esperando obtener la dirección de entrega. ¿Qué valor y de qué tipo recibe realmente, y por qué dejó de ser la dirección?
"""